[tool.poetry]
name = "bert-llm-chat-scripts"
version = "0.1.0"
description = "Ingestion scripts for FAISS index"
authors = []
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.15"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
